### ISSUE TITLE
Not getting baseline results..

### ISSUE THREAD

**Issue by shiva1393** [zerospeech/zerospeech2021_baseline#2]
Hi..
I trained CPC model and kmeans :
CPC:
`python cpc/train.py  --some_inputs`
K-means:
`python CPC_audio-zerospeech/cpc/criterion/clustering/clustering_script.py  --some_inputs`

then i tried to quantize the audio using following command to give this inputs to bert model:
```
python ./scripts/quantize_audio.py \
    checkpoints_mine/clustering_CPC_small_kmeans50/clustering_CPC_small_kmeans50.pt \
    train-clean-100/ \
    quantized/LibriSpeech/train-clean-100/  \
    --file_extension flac
```    
but i'm not getting proper tokens
```
3112-9555-0078	26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26
```

For all utterences  only 26 token activating ...I completed cpc and kmeans models properly. where i'm doing mistake.

**Comment by mmmaat** [comment]
@tuanh208 do you have an idea?

**Comment by tuanh208** [comment]
Hi, 
Are you using your own kmeans checkpoint that you have trained to quantize the audio ?

**Comment by shiva1393** [comment]
@tuanh208   No sir, I'm using baseline scripts only, which provided in zerospeech2021_baseline. Can you tell which part I should check to correct this mistake?

**Comment by tuanh208** [comment]
I mean the checkpoint of kmeans. Normally the kmeans checkpoint have to associate to the right cpc model used in the kmeans training (which can be found in the "pathCheckpoint" arg in the kmeans_checkpoint_args.json file). (Also note that different kmeans training gives different discrete units!)

For example, if you train the cpc model and save the checkpoints to `checkpoints/cpc/checkpoint_100.pt`
and the kmeans checkpoint is saved to `checkpoints/kmeans/kmeans_checkpoint.pt`.
When you quantize the audio using the `kmeans_checkpoint.pt` file, you need to check if the "pathCheckpoint" arg in the file `checkpoints/kmeans/kmeans_checkpoint_args.json` points to the cpc checkpoint (`checkpoints/cpc/checkpoint_100.pt`).

**Comment by shiva1393** [comment]
@tuanh208 Yes sir, I have right checkpoint path for cpc model and  i checked it is loading right path.
For reference :
  "pathCheckpoint": "/data/shiva/zerospeech2021/zerospeech2021_baseline/checkpoints_mine/checkpoint_135.pt",
  "pathOutput": "/data/shiva/zerospeech2021/zerospeech2021_baseline/checkpoints_mine/clustering_CPC_small_kmeans50/clustering_CPC_small_kmeans50.pt",
  
  
  But after training cpc model ,checkpoint_args.json file not created from the given cpc code. So i only manulally added that file. Here is the link [](https://drive.google.com/file/d/1dq602BhG7P5DvZXKg1zFK8LQ3iw50VlE/view?usp=sharing).

**Comment by tuanh208** [comment]
Hmm I may assume that the problem comes from the cpc training.

To verify this, could you please check if the `quantize_audio.py` script works for our checkpoint. 
If that's the case, could you try to train the kmeans on our cpc model to see if it works ?

**Comment by shiva1393** [comment]
ok sir, I will train kmeans on baseline checkpoint and i will inform

**Comment by shiva1393** [comment]
@tuanh208 Hi sir, By taking your baseline model, it is working well. 
  In my case, CPC checkpoint_args.json is not correct. Because CPC code automatically not generating this file. Can you tell where I can save this file in code?

**Comment by MarvinLvn** [comment]
Hi @shiva1393,

You are right, the checkpoint_args.json file wasn't save (which was not the expected behavior).
This [pull request](https://github.com/facebookresearch/CPC_audio/pull/15) should fix the issue.

It just adds two lines in the file **train.py** that you should easily be able to modify yourself.
