### ISSUE TITLE
Converting psuedo units to normal characters ? 

### ISSUE THREAD

**Issue by Enescigdem** [zerospeech/zerospeech2021_baseline#5]
Hello,
I have been trying to get results from pre-trained checkpoints and I have tried run_phonetic.sh.I could not understand the results of this. For example, there are 50 numbers for a line for the audio file. These are 50 centroids of Kmeans but i don't know how I convert these units to phonemes.
Could you please help me?

**Comment by ewan** [comment]
Hi there - the learned units do not correspond directly to phonemes. Can you explain a little more what you are trying to do?


-------- Original message --------
From: Enescigdem ***@***.***>
Date: 2021-07-16 7:51 a.m. (GMT-05:00)
To: bootphon/zerospeech2021_baseline ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [bootphon/zerospeech2021_baseline] Converting psuedo units to normal characters ? (#5)

EXTERNAL EMAIL:

Hello,
I have been trying to get results from pre-trained checkpoints and I have tried run_phonetic.sh.I could not understand the results of this. For example, there are 50 numbers for a line for the audio file. These are 50 centroids of Kmeans but i don't know how I convert these units to phonemes.
Could you please help me?

**Comment by Enescigdem** [comment]
> Hi there - the learned units do not correspond directly to phonemes. Can you explain a little more what you are trying to do?
I will enroll zerospeech 2021 challenge. Before my own solution, I wanted to get baseline scores and understand them using pretrained checkpoints. Could you please help me to understand ?

**Comment by ewan** [comment]
Yes, you can get ABX scores using the evaluation scripts. The ABX scores measure how well the discovered units encode phonemic distinctions. Have you been able to run the evaluation?

**Comment by Enescigdem** [comment]
Sorry for being late return. Where can I find these evaluation scripts and how to run them ?

**Comment by ewan** [comment]
Please refer to the ZeroSpeech 2021 home page:

https://zerospeech.com/2021/#

Which contains download links under "Instructions", and more information about the tasks and evaluation under "Track 1", as well as the linked pape
